[package]
name = "regex"
version = "0.0.0"
description = "A from-scratch regular expression engine"
authors = ["Kian Kasad <kian@kasad.com>"]
edition = "2024"

[dependencies]
log = "0.4.28"

[dev-dependencies]
env_logger = "0.11.8"
paste = "1.0.15"
